export const ENEMY_WEAPON_DEFINITION = {
  id: "enemy-bolt",
  label: "Enemy Bolt",
  firePattern: "alternating",
  cooldown: 1.05,
  projectileSpeed: 48,
  projectileLifetime: 3,
  projectileStyle: "enemy",
  projectileScale: [1, 1, 1],
  collisionRadius: 0.14,
  damage: 14,
  recoil: 0.1,
  spawnOffset: 0.48,
  velocityInheritance: 0.12,
  weaponColor: 0xff926c,
  glowColor: 0xff5c4f,
  trailOpacity: 0.26,
  trailLength: 1.18,
  impactScale: 0.72,
  cameraShake: 0.06,
};
