export const WEAPON_SWITCH_DELAY = 0.28;

export const WEAPON_DEFINITIONS = [
  {
    id: "laser",
    slot: 1,
    label: "Laser",
    firePattern: "dual",
    cooldown: 0.22,
    projectileSpeed: 78,
    projectileLifetime: 2.4,
    projectileStyle: "laser",
    projectileScale: [1, 1, 1],
    collisionRadius: 0.12,
    damage: 16,
    recoil: 0.12,
    spawnOffset: 0.5,
    velocityInheritance: 0.16,
    weaponColor: 0x69dfff,
    glowColor: 0x38b7ff,
    barrelScale: [0.95, 0.95, 1.16],
    muzzleScale: [1.05, 1.05, 1.3],
    glowIntensity: 2.3,
    barrelEmissiveIntensity: 1.2,
    trailOpacity: 0.3,
    trailLength: 1.4,
    impactScale: 0.75,
    cameraShake: 0.12,
    energyCost: 4.2,
  },
  {
    id: "plasma",
    slot: 2,
    label: "Plasma",
    firePattern: "alternating",
    cooldown: 0.48,
    projectileSpeed: 42,
    projectileLifetime: 2.8,
    projectileStyle: "plasma",
    projectileScale: [1.22, 1.22, 1.22],
    collisionRadius: 0.2,
    damage: 28,
    recoil: 0.2,
    spawnOffset: 0.44,
    velocityInheritance: 0.14,
    weaponColor: 0xffb36a,
    glowColor: 0xff7f50,
    barrelScale: [1.2, 1.15, 0.96],
    muzzleScale: [1.35, 1.35, 1.55],
    glowIntensity: 2.8,
    barrelEmissiveIntensity: 1.45,
    trailOpacity: 0.42,
    trailLength: 1.95,
    impactScale: 1.1,
    cameraShake: 0.2,
    energyCost: 9.4,
  },
  {
    id: "rapid-fire",
    slot: 3,
    label: "Rapid Fire",
    firePattern: "alternating",
    cooldown: 0.09,
    projectileSpeed: 88,
    projectileLifetime: 2,
    projectileStyle: "rapid",
    projectileScale: [1, 1, 1],
    collisionRadius: 0.08,
    damage: 8,
    recoil: 0.07,
    spawnOffset: 0.52,
    velocityInheritance: 0.18,
    weaponColor: 0xc7ff6e,
    glowColor: 0x8dff61,
    barrelScale: [0.72, 0.72, 0.9],
    muzzleScale: [0.75, 0.75, 0.95],
    glowIntensity: 2,
    barrelEmissiveIntensity: 1.05,
    trailOpacity: 0.22,
    trailLength: 1.08,
    impactScale: 0.58,
    cameraShake: 0.06,
    energyCost: 1.85,
  },
];

export function getWeaponDefinitionByIndex(index) {
  return WEAPON_DEFINITIONS[index] ?? WEAPON_DEFINITIONS[0];
}
