import { CARROM_BOARD } from '../config/carrom-constants.js';

export const PHYSICS_TUNING = {
  FIXED_TIMESTEP: 1 / 120,
  MAX_SUBSTEPS: 6,
  COIN_MASS: 1,
  STRIKER_MASS: 2.4,
  COIN_RESTITUTION: 0.91,
  STRIKER_RESTITUTION: 0.89,
  WALL_RESTITUTION: 0.8,
  LINEAR_DAMPING: 1.5,
  STOP_SPEED_THRESHOLD: 0.025,
  SLEEP_FRAMES_REQUIRED: 18,
  MIN_VELOCITY_CUTOFF: 0.006,
  MAX_SHOT_SPEED_DEV_TEST: 14.4,
  MAX_BODY_SPEED: 17,
  COLLISION_EVENT_MIN_SPEED: 0.18,
  POCKET_CAPTURE_RADIUS: 0.21,
  POCKET_HALF_ENTRY_RATIO: 0.5,
  POCKET_PULL_RADIUS: 0.38,
  POCKET_PULL_STRENGTH: 5.15,
  POCKET_REMOVE_DELAY: 160,
  BOARD_BOUNDS: {
    minX: -CARROM_BOARD.PLAY_AREA_SIZE / 2,
    maxX: CARROM_BOARD.PLAY_AREA_SIZE / 2,
    minZ: -CARROM_BOARD.PLAY_AREA_SIZE / 2,
    maxZ: CARROM_BOARD.PLAY_AREA_SIZE / 2
  }
};
